name: Bug Report
description: Create a report to help me improve this action or fix a bug
title: "[Bug]: "
labels: ["bug"]
assignees:
  - paambaati
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Detailed description of the bug
      description: Detailed description of the bug
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: Description of what you expected to happen
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Full version of the action you're using 
      placeholder: Example – v1.0.0
    validations:
      required: true
