name: Make major version tag
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  major-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: read tag data
        id: tag-version
        uses: battila7/get-version-action@v2
      - name: push major version tag
        run: |
          git push origin HEAD:refs/heads/${{ steps.tag-version.outputs.major }}
