name: "Release & publish"
on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  release:
    name: Cut a release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: make a release on GitHub
        run: npm_config_yes=true npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: 'GP'
          GIT_COMMITTER_NAME: 'GP'
          GIT_AUTHOR_EMAIL: 'me@httgp.com'
          GIT_COMMITTER_EMAIL: 'me@httgp.com'

  publish:
    name: Publish Action to GitHub marketplace
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: Publish action
        uses: technote-space/release-github-actions@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: 'GP'
          COMMIT_EMAIL: 'me@httgp.com'
          CREATE_MAJOR_VERSION_TAG: false
          CREATE_MINOR_VERSION_TAG: false
          CLEAN_TARGETS: '.[!.]*,test,src,*.ts,*.json,CHANGELOG.md,_config.yml'
